image: atlassian/default-image:3

pipelines:
    default:
      - step:
          script:
            - git remote add github git@github.com:michailkorenev/Rancher-Catalog-Warehouse.git
            - git push github master